# Generated by Django 6.0.3 on 2026-03-16 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('regular', 'REGULAR'), ('premium', 'PREMIUM')], default='regular', max_length=15),
        ),
    ]
