# Generated by Django 6.0.3 on 2026-03-23 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_book_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_type',
            field=models.CharField(choices=[('regular', 'Regular'), ('exclusive', 'Exclusive')], default='regular', max_length=9),
        ),
    ]
