# Generated by Django 6.0.3 on 2026-03-23 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_book_book_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_type',
            field=models.CharField(choices=[('inclusive', 'Inclusive'), ('exclusive', 'Exclusive')], default='inclusive', max_length=9),
        ),
    ]
